name: KeepExperience
main: com.mintodev.keepexperience.Main
version: "1.0.0"
api: ["1.0.13"]
load: POSTWORLD
author: mintodev
description: Keep experience when players die
depend:
  - PowerNukkit

commands:
  keepexperience:
    description: Toggle keep experience feature
    usage: "/keepexperience"
    permission: "keepexperience.cmd"

permissions:
  keepexperience.cmd:
    description: Allow players to turn on/off keep experience feature
    default: op